import Link from "next/link";
import {
  ArrowRight,
  Bell,
  Footprints,
  Heartbeat,
  PersonSimpleRun,
  Timer,
  WarningCircle,
} from "@phosphor-icons/react/dist/ssr";
import {
  getWorkoutAverageHeartRate,
  getWorkoutDurationMs,
  getWorkoutStepCount,
} from "@/lib/dashboard/metrics";
import type { DashboardSnapshot } from "@/lib/dashboard/types";
import { formatDateTime, formatDuration } from "./format";
import styles from "./dashboard.module.css";

type ActivityPanelsProps = {
  snapshot: DashboardSnapshot;
  now: Date;
  timeZone: string;
};

export function ActivityPanels({
  snapshot,
  now,
  timeZone,
}: ActivityPanelsProps) {
  return (
    <div className={styles.activityGrid}>
      <RecentAlerts snapshot={snapshot} timeZone={timeZone} />
      <LatestWorkout snapshot={snapshot} now={now} timeZone={timeZone} />
    </div>
  );
}

function PanelError({ children }: { children: React.ReactNode }) {
  return (
    <div className={styles.inlineError} role="status">
      <WarningCircle size={22} weight="duotone" aria-hidden="true" />
      <div>
        <strong>Unable to load</strong>
        <p>{children}</p>
      </div>
    </div>
  );
}

function RecentAlerts({
  snapshot,
  timeZone,
}: Pick<ActivityPanelsProps, "snapshot" | "timeZone">) {
  const failed = snapshot.failedSections.includes("recent-alerts");

  return (
    <section className={styles.panel} aria-labelledby="recent-alerts-heading">
      <div className={styles.panelHeader}>
        <div>
          <p className={styles.cardEyebrow}>Mobile notifications</p>
          <h2 id="recent-alerts-heading" className={styles.cardTitle}>
            Recent alerts
          </h2>
        </div>
        <span className={styles.panelIcon} aria-hidden="true">
          <Bell size={23} weight="duotone" />
        </span>
      </div>

      {failed ? (
        <PanelError>Your alert history could not be retrieved.</PanelError>
      ) : snapshot.recentAlerts.length === 0 ? (
        <div className={styles.emptyCompact}>
          <strong>No alerts recorded</strong>
          <p>Alerts generated by the Android app will appear here after sync.</p>
        </div>
      ) : (
        <ul className={styles.alertList}>
          {snapshot.recentAlerts.map((alert) => (
            <li key={alert.id}>
              <span className={styles.alertDot} aria-hidden="true" />
              <div>
                <strong>{alert.reason}</strong>
                <p>{formatDateTime(alert.fired_at, timeZone)}</p>
              </div>
              <span className={styles.alertStatus}>
                {alert.dismissed ? "Dismissed" : "Recorded"}
              </span>
            </li>
          ))}
        </ul>
      )}

      <Link className={styles.panelLink} href="/history">
        View alert history
        <ArrowRight size={17} aria-hidden="true" />
      </Link>
    </section>
  );
}

function LatestWorkout({ snapshot, now, timeZone }: ActivityPanelsProps) {
  const failed = snapshot.failedSections.includes("latest-workout");
  const workout = snapshot.latestWorkout;
  const duration = workout ? getWorkoutDurationMs(workout, now) : null;
  const steps = workout ? getWorkoutStepCount(workout) : null;
  const averageHeartRate = workout ? getWorkoutAverageHeartRate(workout) : null;

  return (
    <section className={styles.panel} aria-labelledby="latest-workout-heading">
      <div className={styles.panelHeader}>
        <div>
          <p className={styles.cardEyebrow}>Synchronized activity</p>
          <h2 id="latest-workout-heading" className={styles.cardTitle}>
            Latest workout
          </h2>
        </div>
        <span className={`${styles.panelIcon} ${styles.workoutIcon}`} aria-hidden="true">
          <PersonSimpleRun size={24} weight="duotone" />
        </span>
      </div>

      {failed ? (
        <PanelError>Your latest workout could not be retrieved.</PanelError>
      ) : workout ? (
        <>
          <div className={styles.workoutTopline}>
            <div>
              <strong>{formatDuration(duration)}</strong>
              <span>{formatDateTime(workout.started_at, timeZone)}</span>
            </div>
            <span className={styles.workoutStatus}>{workout.status}</span>
          </div>
          <dl className={styles.workoutMetrics}>
            <div>
              <Timer size={18} weight="duotone" aria-hidden="true" />
              <dt>Duration</dt>
              <dd>{formatDuration(duration)}</dd>
            </div>
            <div>
              <Footprints size={18} weight="duotone" aria-hidden="true" />
              <dt>Steps</dt>
              <dd>{steps === null ? "Not available" : steps.toLocaleString("en-US")}</dd>
            </div>
            <div>
              <Heartbeat size={18} weight="duotone" aria-hidden="true" />
              <dt>Avg. heart rate</dt>
              <dd>
                {averageHeartRate === null
                  ? "Not available"
                  : `${Math.round(averageHeartRate)} bpm`}
              </dd>
            </div>
          </dl>
        </>
      ) : (
        <div className={styles.emptyCompact}>
          <strong>No workouts synchronized</strong>
          <p>Completed mobile workouts will appear here after cloud sync.</p>
        </div>
      )}

      <Link className={styles.panelLink} href="/history">
        View workout history
        <ArrowRight size={17} aria-hidden="true" />
      </Link>
    </section>
  );
}
