package com.example.stressguard.data.local

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import androidx.room.Room
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The migrations, run against real SQLite on a real device.
 *
 * These matter more than most tests here. The database dropped `fallbackToDestructiveMigration()`
 * when the prediction history became an *input* rather than a display: plan §7's risk score counts
 * high-stress days over one or two weeks, so a wipe on upgrade silently resets the recommendation
 * to "not enough data" for a fortnight. The migrations are what stands in for that fallback, and a
 * broken one throws on the user's device at first launch after an update — the one place it cannot
 * be caught.
 *
 * **Not** written with `MigrationTestHelper`. That builds the starting database from exported
 * schema JSON, and versions 1 and 2 shipped with `exportSchema = false`, so no JSON for them
 * exists or can be recovered without rebuilding old commits. Fabricating it would mean testing the
 * migrations against a hand-written description of the old schema rather than the old schema.
 *
 * These tests instead create the old database with the DDL those versions actually shipped, then
 * open it *through Room* with the real migrations attached. That is the exact path a user's device
 * takes on update, and Room's own validation is the assertion: if the migrated schema does not
 * match what version 3 expects, `Room.build().openHelper` throws
 * `IllegalStateException: Migration didn't properly handle…` before any test code runs.
 */
@RunWith(AndroidJUnit4::class)
class StressGuardMigrationTest {

    private val name = "migration-test.db"
    private val context: Context
        get() = InstrumentationRegistry.getInstrumentation().targetContext

    private val recordedAt = 1_785_056_400_000L

    @Before
    fun deleteAnyLeftovers() {
        context.deleteDatabase(name)
    }

    @After
    fun cleanUp() {
        context.deleteDatabase(name)
    }

    /**
     * The three tables version 1 shipped, before `activityLevel` and `daily_step_totals`.
     *
     * Taken from the entity definitions at commit `2156cb6`, in the form Room generates: backticked
     * identifiers, `INTEGER PRIMARY KEY AUTOINCREMENT` for the autogenerated ids, and the indices
     * the entities declared.
     */
    private fun SQLiteDatabase.createVersion1() {
        execSQL(
            "CREATE TABLE IF NOT EXISTS `stress_predictions` " +
                "(`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`recordedAtEpochMs` INTEGER NOT NULL, `label` TEXT NOT NULL, " +
                "`classIndex` INTEGER NOT NULL, `confidence` REAL NOT NULL, " +
                "`probabilities` TEXT NOT NULL, `modelVersion` TEXT NOT NULL, " +
                "`heartRate` INTEGER NOT NULL, `dailySteps` INTEGER NOT NULL, " +
                "`sleepHours` REAL NOT NULL, `outOfTrainingRange` INTEGER NOT NULL, " +
                "`synced` INTEGER NOT NULL)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_stress_predictions_recordedAtEpochMs` " +
                "ON `stress_predictions` (`recordedAtEpochMs`)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_stress_predictions_synced` " +
                "ON `stress_predictions` (`synced`)"
        )
        execSQL(
            "CREATE TABLE IF NOT EXISTS `latency_metrics` " +
                "(`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`recordedAtEpochMs` INTEGER NOT NULL, `preprocessingMs` INTEGER NOT NULL, " +
                "`inferenceMs` INTEGER NOT NULL, `uiUpdateMs` INTEGER NOT NULL, " +
                "`receiveToPredictionMs` INTEGER NOT NULL, `predictionToAlertMs` INTEGER, " +
                "`totalMs` INTEGER NOT NULL, `coldStart` INTEGER NOT NULL, " +
                "`synced` INTEGER NOT NULL)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_latency_metrics_recordedAtEpochMs` " +
                "ON `latency_metrics` (`recordedAtEpochMs`)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_latency_metrics_synced` " +
                "ON `latency_metrics` (`synced`)"
        )
        execSQL(
            "CREATE TABLE IF NOT EXISTS `alert_events` " +
                "(`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`firedAtEpochMs` INTEGER NOT NULL, `reason` TEXT NOT NULL, " +
                "`highCountInWindow` INTEGER NOT NULL, `windowSize` INTEGER NOT NULL, " +
                "`modelVersion` TEXT NOT NULL, `dismissed` INTEGER NOT NULL, " +
                "`synced` INTEGER NOT NULL)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_alert_events_firedAtEpochMs` " +
                "ON `alert_events` (`firedAtEpochMs`)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_alert_events_synced` " +
                "ON `alert_events` (`synced`)"
        )
    }

    /**
     * @param activityLevel omitted for version 1, which had no such column. It is NOT NULL with no
     *   SQL default from version 2, so the column list has to match the version being seeded.
     */
    private fun SQLiteDatabase.insertPrediction(
        label: String = "stressed",
        activityLevel: Int? = null,
    ) {
        val extraColumn = if (activityLevel == null) "" else ", activityLevel"
        val extraValue = if (activityLevel == null) "" else ", $activityLevel"
        execSQL(
            "INSERT INTO stress_predictions (recordedAtEpochMs, label, classIndex, confidence, " +
                "probabilities, modelVersion, heartRate, dailySteps, sleepHours, " +
                "outOfTrainingRange, synced$extraColumn) " +
                "VALUES (?, ?, 1, 0.9, '0.1,0.9', 'v1', 88, 4200, 7.5, 0, 0$extraValue)",
            arrayOf<Any>(recordedAt, label),
        )
    }

    /**
     * The tables version 2 shipped: version 1 plus `activityLevel` and `daily_step_totals`.
     *
     * Written out rather than produced by running [StressGuardDatabase.MIGRATION_1_2], which would
     * make the version-2 test partly circular — it would verify the migration against its own
     * output. Every real version 2 database was in any case created fresh by Room, because the
     * 1→2 upgrade went through destructive fallback, so `activityLevel` is declared inline with no
     * SQL default. Taken from `app/schemas/…/3.json`, which still carries this table unchanged.
     */
    private fun SQLiteDatabase.createVersion2() {
        createVersion1()
        execSQL("DROP TABLE `stress_predictions`")
        execSQL(
            "CREATE TABLE IF NOT EXISTS `stress_predictions` " +
                "(`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                "`recordedAtEpochMs` INTEGER NOT NULL, `label` TEXT NOT NULL, " +
                "`classIndex` INTEGER NOT NULL, `confidence` REAL NOT NULL, " +
                "`probabilities` TEXT NOT NULL, `modelVersion` TEXT NOT NULL, " +
                "`heartRate` INTEGER NOT NULL, `dailySteps` INTEGER NOT NULL, " +
                "`activityLevel` INTEGER NOT NULL, `sleepHours` REAL NOT NULL, " +
                "`outOfTrainingRange` INTEGER NOT NULL, `synced` INTEGER NOT NULL)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_stress_predictions_recordedAtEpochMs` " +
                "ON `stress_predictions` (`recordedAtEpochMs`)"
        )
        execSQL(
            "CREATE INDEX IF NOT EXISTS `index_stress_predictions_synced` " +
                "ON `stress_predictions` (`synced`)"
        )
        execSQL(
            "CREATE TABLE IF NOT EXISTS `daily_step_totals` " +
                "(`date` TEXT NOT NULL, `steps` INTEGER NOT NULL, " +
                "`updatedAtEpochMs` INTEGER NOT NULL, PRIMARY KEY(`date`))"
        )
    }

    /** Builds a database at [version] with the DDL that version shipped, then closes it. */
    private fun createOldDatabase(version: Int, seed: SQLiteDatabase.() -> Unit = {}) {
        val file = context.getDatabasePath(name)
        file.parentFile?.mkdirs()
        val db = SQLiteDatabase.openOrCreateDatabase(file, null)
        try {
            if (version >= 2) db.createVersion2() else db.createVersion1()
            db.seed()
            db.version = version
        } finally {
            db.close()
        }
    }

    /**
     * Opens the database the way the app does.
     *
     * Room runs the migrations and then validates the result against version 3's expected schema,
     * so simply reaching the first query is a meaningful assertion.
     */
    private fun openThroughRoom(): StressGuardDatabase =
        Room.databaseBuilder(context, StressGuardDatabase::class.java, name)
            .addMigrations(*StressGuardDatabase.migrations())
            .build()

    /**
     * The whole point: a user's history survives the upgrade.
     *
     * Asserts the rows are still there, not merely that the migration ran — a migration that
     * dropped and recreated the table would satisfy Room's schema validation and still fail the
     * user.
     */
    @Test
    fun predictionHistorySurvivesTheUpgradeFromVersion1() = runTest {
        createOldDatabase(version = 1) { insertPrediction() }

        val database = openThroughRoom()
        try {
            val stored = database.stressPredictions().latest(10).single()
            assertEquals(recordedAt, stored.recordedAtEpochMs)
            assertEquals("stressed", stored.label)
            assertEquals(88, stored.heartRate)
            assertEquals(
                "rows predating the column should read as 'not recorded'",
                0,
                stored.activityLevel,
            )
            assertFalse("an unsynced row must stay queued across an upgrade", stored.synced)
        } finally {
            database.close()
        }
    }

    /** The version every current install is actually on. */
    @Test
    fun predictionHistorySurvivesTheUpgradeFromVersion2() = runTest {
        createOldDatabase(version = 2) { insertPrediction("not_stressed", activityLevel = 8000) }

        val database = openThroughRoom()
        try {
            assertEquals(1, database.stressPredictions().count())
            assertEquals("not_stressed", database.stressPredictions().latest(1).single().label)
        } finally {
            database.close()
        }
    }

    /**
     * The migrated database is usable, not merely structurally valid.
     *
     * Room's validation compares schemas; this writes through the DAO, which is what catches a
     * column Room can bind but SQLite rejects.
     */
    @Test
    fun theMigratedDatabaseAcceptsAChecklist() = runTest {
        createOldDatabase(version = 2)

        val database = openThroughRoom()
        try {
            val dao = database.healthChecklists()
            dao.save(
                HealthChecklistEntity(
                    smoking = true,
                    heartCondition = true,
                    updatedAtEpochMs = recordedAt,
                )
            )

            val stored = dao.current()!!
            assertTrue(stored.smoking)
            assertTrue(stored.heartCondition)
            assertFalse(stored.diabetes)
            assertEquals(1, dao.countUnsynced())

            // The singleton key is what makes a re-save an edit rather than a second answer.
            dao.save(stored.copy(smoking = false))
            assertFalse(dao.current()!!.smoking)
            assertEquals("a second save must not create a second row", 1, dao.unsynced().size)
        } finally {
            database.close()
        }
    }

    /** The day totals added in version 2 are still there and still usable afterwards. */
    @Test
    fun theDayTotalsTableSurvivesTheUpgrade() = runTest {
        createOldDatabase(version = 2) {
            execSQL(
                "INSERT INTO daily_step_totals (date, steps, updatedAtEpochMs) " +
                    "VALUES ('2026-07-25', 9000, ?)",
                arrayOf<Any>(recordedAt),
            )
        }

        val database = openThroughRoom()
        try {
            assertEquals(9000, database.dailyStepTotals().totalFor("2026-07-25"))
        } finally {
            database.close()
        }
    }
}
